### ISSUE TITLE
Allow making item frames invisible and make them display custom name

### ISSUE THREAD

**Issue by windowsfan6** [VoxelForge/VoxelForge#103]
In Minecraft, there is an item frame property which makes item frames invisible. It's great for creativity (for example, it allows for items to lay in the ground without item frame being visible).

Additionally, in MC, renamed items display a name given via anvil when put in item frame. I think it's very useful and it could've been added as well. It helps identifying items with non-obvious name (such as Potato named as Fries, for example).

**Comment by DragonWrangler1** [comment]
The invisible item frames will be coming in the next release.
