### ISSUE TITLE
(Bug) Game crashes when right clicking a horse

### ISSUE THREAD

**Issue by windowsfan6** [VoxelForge/VoxelForge#106]
Was casually playing, and then the horse crashed the game after right clicking it. Can't provide a log since I was playing on the phone, and I don't have GitHub here.

**Comment by DragonWrangler1** [comment]
I'll see if I can reproduce. Shouldn't be too hard.

**Comment by DragonWrangler1** [comment]
K, found the fix.

**Comment by DragonWrangler1** [comment]
Should be fixed now.
