### ISSUE TITLE
New bundles textures

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#113]
@crispiebacon Since the bundles are in game already and their textures only differ 22% from MC which cuts it very very close. I need these new textures kind of soon. The lowest it could possibly be 20%

**Comment by DragonWrangler1** [comment]
@crispiebacon How are they coming along ?

**Comment by crispiebacon** [comment]
I'm struggling coming up with a design for them.

**Comment by crispiebacon** [comment]
Ok. Textures done. I'll upload them to the repo once I get the others done.

**Comment by DragonWrangler1** [comment]
Nice. I look forward to seeing them.

**Comment by crispiebacon** [comment]
Bundles textures up
