### ISSUE TITLE
Make caves not completely dark.

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#114]
Not exactly a bug, but it does make exploring caves harder. Like lots.

**Comment by Alphizi** [comment]
What would a cave without lighting look like in real life? Minecraft has never been a casual game, artificially lighting will ruin the game.

**Comment by DragonWrangler1** [comment]
> What would a cave without lighting look like in real life? Minecraft has never been a casual game, artificially lighting will ruin the game.

This game is meant to perfectly replicate MC. So we will be adding cave lighting, however it will be an optional setting.
