### ISSUE TITLE
Some flowers have broken textures

### ISSUE THREAD

**Issue by windowsfan6** [VoxelForge/VoxelForge#127]
Just like in title. This screenshot explains it all.
![minetest_ks2NX4CLIP](https://github.com/user-attachments/assets/2f1b6c48-a093-4ffe-ac7b-999726b02cb9)

**Comment by DragonWrangler1** [comment]
What MT version is this ?

**Comment by DragonWrangler1** [comment]
Feel free to re-open it if the newest commit didn't fix it on your end.
