### ISSUE TITLE
Update Pixel Perfection

### ISSUE THREAD

**Issue by Alphizi** [VoxelForge/VoxelForge#143]
VoxelForge uses the original pixel perfection, one of the best texture packs for Minecraft. The original version hasn't been updated in a long time. Someone made a fork and is developing the project in a more updated and fresh way. It would be nice to update the old version to the new one.

The game is literally transformed, much more perfect and nice visuals.
https://modrinth.com/resourcepack/pixel-perfection-legacy
Creative Commons Attribution-Share Alike 4.0 International License

**Comment by Alphizi** [comment]
![2024-09-04_12 55 33](https://github.com/user-attachments/assets/77999bc5-f165-42b0-840e-2628717d2bfc)
![2024-09-04_12 55 46](https://github.com/user-attachments/assets/624db298-b66f-49aa-a6c0-031da9827b0d)
![2024-09-04_12 56 00](https://github.com/user-attachments/assets/5ed76183-8a55-4317-a891-da9011958675)
![2024-09-04_12 56 25](https://github.com/user-attachments/assets/d2aafc56-1f71-4fac-9dc4-713c8a9bf94b)
![2024-09-04_12 56 37](https://github.com/user-attachments/assets/02b6937c-6b70-4222-8032-582db77b1530)
![2024-09-04_12 56 52](https://github.com/user-attachments/assets/0e42cdb5-9b91-44d7-8620-1ddae4080d78)
![2024-09-04_12 57 10](https://github.com/user-attachments/assets/cee44211-e7d1-4548-824e-9ef9cdff8a36)

**Comment by DragonWrangler1** [comment]
We will be updating the textures, but probably not to the new Pixel Perfection. @crispiebacon is working on a new texture pack for VoxelForge.
