### ISSUE TITLE
Texture License Change.

### ISSUE THREAD

**Issue by crispiebacon** [VoxelForge/VoxelForge#161]
@DragonWrangler1 and to everyone. I'm making my own free license for the textures. So you will need to update the licensing accordingly.

**Comment by DragonWrangler1** [comment]
Um... So why are there all those images right in the main directory ?!

**Comment by crispiebacon** [comment]
Sorry. I accidentally did this one instead of my repo.

**Comment by DragonWrangler1** [comment]
No harm done.

**Comment by crispiebacon** [comment]
Ok license is ready. Please update it asap.
