### ISSUE TITLE
Texture change needed.

### ISSUE THREAD

**Issue by crispiebacon** [VoxelForge/VoxelForge#176]
I made a small mistake with the wolf armor textures. I forgot to check to see how much different they were from mc, so. Turns out they are only 10%. Which means we need to change them asap.

**Comment by crispiebacon** [comment]
Textures updated closest one is now 25% instead of 10% and this batch used Pixel Perfection as the template.

**Comment by DragonWrangler1** [comment]
K. Patch release will be ready shortly.
