### ISSUE TITLE
Add Pale Garden biome

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#219]
- [x] Biome Registry.
 - [x] Pale Wood.
 - [x] Creaking Model.
 - [x] Pale Carpet.
 - [x] Creaking heart.
 - [x] Pale vines.
 - [x] Tree Schematics.
 - [ ] Ambient sounds.
 - [x] Add Grass decorations.
 - [x] Add moss decorations.
 - [x] Allow Creaking heart to become active when between two pale wood logs (of any type) that are facing the same direction.
 - [ ] Ambient particles.
 - [x] resin.
 - [x] eyeblossoms.

**Comment by DragonWrangler1** [comment]
@crispiebacon 

We kinda need textures soon.

**Comment by DragonWrangler1** [comment]
Current Pale Garden prototype. (And yes. I am using MC textures atm, for testing)

![Screenshot from 2024-10-03 11-22-16](https://github.com/user-attachments/assets/7921a8ca-5da6-4b70-83c0-f2e2353b65d7)

**Comment by crispiebacon** [comment]
> Current Pale Garden prototype. (And yes. I am using MC textures atm, for testing)
> 
> ![Screenshot from 2024-10-03 11-22-16](https://private-user-images.githubusercontent.com/146014546/373369732-7921a8ca-5da6-4b70-83c0-f2e2353b65d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODcyNzgsIm5iZiI6MTcyNzk4Njk3OCwicGF0aCI6Ii8xNDYwMTQ1NDYvMzczMzY5NzMyLTc5MjFhOGNhLTVkYTYtNGI3MC04M2MwLWYyZTIzNTNiNjVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QyMDIyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTgxNDc3ODk5ZjQzM2NiOTRjNDJjNTk2ZjY1ODYxMDkxNjkwNWNkZDc5N2QzOTk5ZmMxMmEzZDQ3ZTMxM2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mjjo26cx4dvpAZ4xRHqCRtdkRZ_D9YUPk4eT9z3U1YM)

That looks good. I'll try to keep the new textures similar. Also thanks for releasing the update.
