### ISSUE TITLE
Font too big

### ISSUE THREAD

**Issue by JoseDouglas26** [VoxelForge/VoxelForge#244]
**Description**
The font of all the texts in the game are exaggeratedly large for some reason. With other games, everything is normal.

**To Reproduce**
Join the game or open the creative inventory

**Expected behavior**
Have normal sized fonts
![Screenshot_22](https://github.com/user-attachments/assets/04b33e1f-8edc-49e9-819f-ad76f5c4b121)
![Screenshot_23](https://github.com/user-attachments/assets/e74d23b8-0e7a-4d69-9d1c-a5808dd4df93)
![Screenshot_24](https://github.com/user-attachments/assets/856dedc3-ecd8-4c09-94fd-035885812bcc)
![Uploading Screenshot_26.png…]()

**Comment by DragonWrangler1** [comment]
@JoseDouglas26 

Please check The settings menu for the following settings under the VoxelForge area.

'Font Size'
'Chat Font Size'
'Font Shadow Size'

VoxelForge changes the font size to make that font more readable... Though I thought that I shrunk it in one of the weekly releases a while back... I'll look into it.

For now the settings should work.
