### ISSUE TITLE
Concept for new textures.

### ISSUE THREAD

**Issue by crispiebacon** [VoxelForge/VoxelForge#50]
Here's a couple concepts for new textures. I made these to be very very close to mc.

A few comparisons. Left is the version I made. Right is mc.

**Comment by DragonWrangler1** [comment]
top 3: No. Very very minecraft like. I can hardly tell a difference. Maybe change the 4th as well...

**Comment by crispiebacon** [comment]
how about these ?

![grass_top_compare](https://github.com/user-attachments/assets/635f69db-b4a4-4d67-a9fb-42b152d05d88)
![grass_side_compare](https://github.com/user-attachments/assets/00225889-c839-4dab-811a-27ca6827a062)
![grass_compare](https://github.com/user-attachments/assets/177bc5b8-22e4-4d65-bc33-f222b7c94e76)
![dirt_compare](https://github.com/user-attachments/assets/df4b1232-4f1b-42c5-84fd-026ed4f27a4a)

**Comment by DragonWrangler1** [comment]
Dirt is better. Others are still too close.

**Comment by crispiebacon** [comment]
ok.

**Comment by crispiebacon** [comment]
You can find the comparisons here.  https://github.com/crispiebacon/voxelforge-resource-pack/issues/2

**Comment by DragonWrangler1** [comment]
I suppose a few can be added in 0.4.0

**Comment by DragonWrangler1** [comment]
I removed the images since the discussion will be continued in your repo.
