### ISSUE TITLE
Crash: when spawning villages

### ISSUE THREAD

**Issue by crispiebacon** [VoxelForge/VoxelForge#57]
AsyncErr: Lua: Runtime error from mod '??' in callback on_chat_message(): "Unknown node: vlf_stairs:slab_sprucewood_top"
stack traceback:
	[C]: in function '__index'
	...1929/usr/bin/../share/minetest/builtin/common/item_s.lua:229: in function <...1929/usr/bin/../share/minetest/builtin/common/item_s.lua:228>
	[C]: in function 'old_add_node'
	...t/games/voxelforge/mods/ITEMS/vlf_sculk/sculk_sensor.lua:408: in function 'add_node'
	...test/games/voxelforge/mods/MAPGEN/vlf_villages/paths.lua:212: in function 'place_path'
	...test/games/voxelforge/mods/MAPGEN/vlf_villages/paths.lua:340: in function 'paths_new'
	.../games/voxelforge/mods/MAPGEN/vlf_villages/buildings.lua:556: in function 'place_schematics_new'
	...etest/games/voxelforge/mods/MAPGEN/vlf_villages/init.lua:42: in function 'build_a_settlement'
	...etest/games/voxelforge/mods/MAPGEN/vlf_villages/init.lua:92: in function 'func'
	...est/1929/usr/bin/../share/minetest/builtin/game/chat.lua:79: in function <...est/1929/usr/bin/../share/minetest/builtin/game/chat.lua:52>
	...29/usr/bin/../share/minetest/builtin/common/register.lua:26: in function <...29/usr/bin/../share/minetest/builtin/common/register.lua:12>

**Comment by DragonWrangler1** [comment]
It's getting to the point where this version added more bugs than it fixes.
