### ISSUE TITLE
(Bug) Fonts are gigantic

### ISSUE THREAD

**Issue by windowsfan6** [VoxelForge/VoxelForge#61]
Just like in title.

![obraz](https://github.com/user-attachments/assets/3867499d-ba5b-44bc-a35e-84e3d837934b)

Idk what causes this, but it looks very cursed. The version this bug occurs is 0.4.0-pre2

**Comment by DragonWrangler1** [comment]
pr [https://github.com/VoxelForge/VoxelForge/pull/38](url) fixes that. That's the default chat size for voxelforge. the settings can modify the font size.

**Comment by DragonWrangler1** [comment]
Feel free to open if adjusting the setting doesn't help any.
