### ISSUE TITLE
Add tripwire.

### ISSUE THREAD

**Issue by DragonWrangler1** [VoxelForge/VoxelForge#87]
#86 depends on this. Due to the trial chambers. and jungle temple.

**Comment by DragonWrangler1** [comment]
@crispiebacon I need you to make some tripwire textures. Something that makes them not very noticable.

**Comment by crispiebacon** [comment]
I need models first.

**Comment by crispiebacon** [comment]
I'm working on the models.

**Comment by DragonWrangler1** [comment]
Thanks.

**Comment by DragonWrangler1** [comment]
I plan for all 3 models. If that's alright with you.

**Comment by crispiebacon** [comment]
I'll go ahead and make all three just incase you change your mind.

**Comment by crispiebacon** [comment]
Done. see https://github.com/crispiebacon/voxelforge-tripwire-media
